apiVersion: v1
kind: Pod
metadata:
  name: chykee67todoapp
  labels:
    app: chykee67todoapp
spec:
  containers:
    - name: backend-server
      image: chykee67/django_graphql_app:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 3031
          name: backend-port
      volumeMounts:
        - name: app-storage
          mountPath: /app/media

  volumes:
    - name: app-storage
      persistentVolumeClaim:
        claimName: app-pvc