services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      #- my-network
      - webapp-network
  
  #web-app:
   # image: ubuntu:latest
    #volumes:
     # - ./backend:/backend:ro
    #entrypoint: ["backend/backend_script.sh"]
    #networks:
    #  - my-network

networks:
  webapp-network:
    external: true
 # my-network:
  #  driver: bridge