services:
  backend_server:
    image: chykee67/django_graphql_app:latest
    container_name: backend_server
    pull_policy: always
    ports:
      - "3031:3031"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./media
        target: /app/media

      #- type: bind
      #  source: ./cookies.py
      #  target: /usr/local/lib/python3.13/http/cookies.py

      #- type: bind
      #  source: ./utils.py
      #  target: /usr/local/lib/python3.13/site-packages/graphql_jwt/utils.py

      #- type: bind
      #  source: ./response.py
      #  target: /usr/local/lib/python3.13/site-packages/django/http/response.py
    depends_on:
      - frontend_server
    networks:
      - app-network


  frontend_server:
    image: chykee67/nextjs_app:latest
    container_name: frontend_server
    pull_policy: always
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network


  nginx_server:
    image: nginx:latest
    container_name: nginx_server
    pull_policy: always
    ports:
      - "80:80"
      - "5432"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./media
        target: /media
    depends_on:
      - backend_server
    networks:
      - app-network



networks:
  app-network:
    driver: bridge