[uwsgi]
socket=myapp-backend-service:3031 #for use with nginx
#http=127.0.0.1:3031 #for running uwsgi as standalone server
chdir=/backend/mybasicapp
wsgi-file=mybasicapp/wsgi.py
processes=4
threads=2
stats=127.0.0.1:9191