[uwsgi]

#http=127.0.0.1:3031 #for running uwsgi as standalone server
socket=0.0.0.0:3031

chdir=/app/backend/mybasicapp_graphql

module=mybasicapp_graphql.wsgi:application

master=true

plugin=python

wsgi-file=mybasicapp_graphql/wsgi.py

processes=4

threads=2

stats=127.0.0.1:9191