# Generated by Django 5.1.6 on 2025-03-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.SlugField(allow_unicode=True, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
