# Generated by Django 5.1.6 on 2025-03-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_delete_todomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(help_text='Format: YYYY-MM-DD HH:MM'),
        ),
    ]
