apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend
  namespace: practice-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      containers:
        - name: backend-server
          image: chykee67/backend_server:latest
          volumeMounts:
            - name: myapp-volume
              mountPath: /myapp-media/
      volumes:
        - name: myapp-volume
          persistentVolumeClaim:
            claimName: myapp-pvc