#Persistent volume for the backend
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-pv
  namespace: practice-ns
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5M
  claimRef:
    name: myapp-pvc
    namespace: practice-ns
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values: ['minikube']
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /myapp-media/

---

#Persistent volume claim for the backend
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
  namespace: practice-ns
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: myapp-pv
  storageClassName: ""
  volumeMode: Filesystem
  resources:
    limits:
      storage: 5M
    requests:
      storage: 5M

---

#Backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend
  namespace: practice-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      containers:
        - name: backend-server
          image: chykee67/backend_server:latest
          volumeMounts:
            - name: myapp-volume
              mountPath: /media/
      volumes:
        - name: myapp-volume
          persistentVolumeClaim:
            claimName: myapp-pvc