apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-pv
  namespace: practice-ns
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5M
  claimRef:
    name: myapp-pvc
    namespace: practice-ns
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values: ['minikube']
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /myapp-media/
