apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-proxy
  namespace: practice-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-proxy
  template:
    metadata:
      labels:
        app: myapp-proxy
    spec:
      containers:
        - name: nginx-proxy
          image: chykee67/proxy:latest
          volumeMounts:
            - name: myproxy-volume
              mountPath: /myapp-media/
      volumes:
        - name: myproxy-volume
          persistentVolumeClaim:
            claimName: myapp-pvc