user nginx;

worker_processes auto;

error_log /var/log/nginx/error.log notice;

pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;
	server_tokens build; # Recommended practice is to turn this off


    keepalive_timeout 65;

    #gzip on;

    #ssl_session_cache shared:SSL:10m;
    #ssl_session_timeout 10m;

    server {
        listen 80 default_server;
        #server_name localhost;
        server_name kandra-gonadotropic-ethelene.ngrok-free.dev;

        location / {
            proxy_pass http://localhost:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /graphql {
            include uwsgi_params;
            uwsgi_pass localhost:3031;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /media {
            alias /app/media;
        }

        location /static {
            alias /app/static;
        }
    }

    #server {
    #    listen 443 ssl;
    #    server_name localhost;

#        ssl_certificate ...;
#        ssl_private_key ...;
#    }
}

#stream {
#    upstream backend_db {
#        server 192.168.1.33:5432;
#        #server 192.168.0.174:5432;
#    }

#    server {
#        listen 5432;
#        proxy_pass backend_db;
#    }
##}