services:
  backend_server:
    image: chykee67/django_graphql_app:latest
    container_name: backend_server
    pull_policy: always
    ports:
      - "3031:3031"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ../media
        target: /app/media
      - type: bind
        source: ../static
        target: /app/static
    depends_on:
      - frontend_server
    networks:
      - app-network


  frontend_server:
    image: chykee67/nextjs_app:latest
    container_name: frontend_server
    pull_policy: always
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network


  nginx_server:
    image: chykee67/nginx_server:latest
    container_name: nginx_server
    pull_policy: always
    ports:
      - "80:80"
      - "5432"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ../media
        target: /media
      - type: bind
        source: ../static
        target: /static
    depends_on:
      - backend_server
    networks:
      - app-network



networks:
  app-network:
    driver: bridge